// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kv_store.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	kv_store.proto

It has these top-level messages:
	StringRequest
	StringResponse
	HashFieldRequest
	HashResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type StringRequest struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *StringRequest) Reset()                    { *m = StringRequest{} }
func (m *StringRequest) String() string            { return proto1.CompactTextString(m) }
func (*StringRequest) ProtoMessage()               {}
func (*StringRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StringRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type StringResponse struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *StringResponse) Reset()                    { *m = StringResponse{} }
func (m *StringResponse) String() string            { return proto1.CompactTextString(m) }
func (*StringResponse) ProtoMessage()               {}
func (*StringResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StringResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type HashFieldRequest struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Field string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
}

func (m *HashFieldRequest) Reset()                    { *m = HashFieldRequest{} }
func (m *HashFieldRequest) String() string            { return proto1.CompactTextString(m) }
func (*HashFieldRequest) ProtoMessage()               {}
func (*HashFieldRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HashFieldRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HashFieldRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type HashResponse struct {
	Value map[string]string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *HashResponse) Reset()                    { *m = HashResponse{} }
func (m *HashResponse) String() string            { return proto1.CompactTextString(m) }
func (*HashResponse) ProtoMessage()               {}
func (*HashResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HashResponse) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto1.RegisterType((*StringRequest)(nil), "turing.StringRequest")
	proto1.RegisterType((*StringResponse)(nil), "turing.StringResponse")
	proto1.RegisterType((*HashFieldRequest)(nil), "turing.HashFieldRequest")
	proto1.RegisterType((*HashResponse)(nil), "turing.HashResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for KVStore service

type KVStoreClient interface {
	Get(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error)
	HashGet(ctx context.Context, in *HashFieldRequest, opts ...grpc.CallOption) (*StringResponse, error)
	HashGetAll(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*HashResponse, error)
}

type kVStoreClient struct {
	cc *grpc.ClientConn
}

func NewKVStoreClient(cc *grpc.ClientConn) KVStoreClient {
	return &kVStoreClient{cc}
}

func (c *kVStoreClient) Get(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := grpc.Invoke(ctx, "/turing.KVStore/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) HashGet(ctx context.Context, in *HashFieldRequest, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := grpc.Invoke(ctx, "/turing.KVStore/HashGet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kVStoreClient) HashGetAll(ctx context.Context, in *StringRequest, opts ...grpc.CallOption) (*HashResponse, error) {
	out := new(HashResponse)
	err := grpc.Invoke(ctx, "/turing.KVStore/HashGetAll", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for KVStore service

type KVStoreServer interface {
	Get(context.Context, *StringRequest) (*StringResponse, error)
	HashGet(context.Context, *HashFieldRequest) (*StringResponse, error)
	HashGetAll(context.Context, *StringRequest) (*HashResponse, error)
}

func RegisterKVStoreServer(s *grpc.Server, srv KVStoreServer) {
	s.RegisterService(&_KVStore_serviceDesc, srv)
}

func _KVStore_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turing.KVStore/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).Get(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_HashGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HashFieldRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).HashGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turing.KVStore/HashGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).HashGet(ctx, req.(*HashFieldRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KVStore_HashGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KVStoreServer).HashGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/turing.KVStore/HashGetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KVStoreServer).HashGetAll(ctx, req.(*StringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _KVStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "turing.KVStore",
	HandlerType: (*KVStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _KVStore_Get_Handler,
		},
		{
			MethodName: "HashGet",
			Handler:    _KVStore_HashGet_Handler,
		},
		{
			MethodName: "HashGetAll",
			Handler:    _KVStore_HashGetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kv_store.proto",
}

func init() { proto1.RegisterFile("kv_store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x2e, 0x8b, 0x2f,
	0x2e, 0xc9, 0x2f, 0x4a, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x29, 0x2d, 0xca,
	0xcc, 0x4b, 0x57, 0x52, 0xe4, 0xe2, 0x0d, 0x2e, 0x01, 0xb1, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b,
	0x4b, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40,
	0x4c, 0x25, 0x35, 0x2e, 0x3e, 0x98, 0x92, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x11, 0x2e,
	0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0xa8, 0x2a, 0x08, 0x47, 0xc9, 0x8a, 0x4b, 0xc0, 0x23, 0xb1,
	0x38, 0xc3, 0x2d, 0x33, 0x35, 0x27, 0x05, 0xa7, 0x69, 0x20, 0xbd, 0x69, 0x20, 0x15, 0x12, 0x4c,
	0x10, 0xbd, 0x60, 0x8e, 0x52, 0x3d, 0x17, 0x0f, 0x48, 0x2f, 0xdc, 0x06, 0x53, 0x84, 0x0d, 0xcc,
	0x1a, 0xdc, 0x46, 0xf2, 0x7a, 0x10, 0xe7, 0xea, 0x21, 0x2b, 0xd2, 0x0b, 0x03, 0xa9, 0x70, 0xcd,
	0x2b, 0x29, 0xaa, 0x84, 0x3a, 0x41, 0xca, 0x82, 0x8b, 0x0b, 0x21, 0x88, 0xdd, 0x72, 0x88, 0xb1,
	0x4c, 0x48, 0x0e, 0xb7, 0x62, 0xb2, 0x60, 0x34, 0xda, 0xcb, 0xc8, 0xc5, 0xee, 0x1d, 0x16, 0x0c,
	0x0a, 0x21, 0x21, 0x33, 0x2e, 0x66, 0xf7, 0xd4, 0x12, 0x21, 0x51, 0x98, 0xa5, 0x28, 0x01, 0x24,
	0x25, 0x86, 0x2e, 0x0c, 0x71, 0x8d, 0x12, 0x83, 0x90, 0x2d, 0x17, 0x3b, 0xc8, 0x7d, 0x20, 0xbd,
	0x12, 0xc8, 0x0e, 0x46, 0x0e, 0x11, 0x3c, 0xda, 0xad, 0xb9, 0xb8, 0xa0, 0xda, 0x1d, 0x73, 0x72,
	0x70, 0xd9, 0x2e, 0x82, 0x2d, 0x24, 0x94, 0x18, 0x9c, 0x14, 0xa3, 0xe4, 0xd3, 0x33, 0x4b, 0x32,
	0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x13, 0x8b, 0x52, 0x73, 0x72, 0x52, 0x8b, 0xf4, 0x21,
	0x6a, 0xf5, 0xc1, 0x51, 0x9e, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xbc,
	0xad, 0x26, 0x4a, 0x0b, 0x02, 0x00, 0x00,
}
